---
- name: Preprare Development Machine
  hosts: machine

  tasks:
    - name: Allow HTTP traffic
      become: yes
      community.general.ufw:
        rule: allow
        name: http

    - name: Allow HTTPS traffic
      become: yes
      community.general.ufw:
        rule: allow
        name: https

    - name: Allow port 873 [Rsync Endpoint]
      community.general.ufw:
        rule: allow
        port: "873"
        proto: tcp

    - name: Allow port 5000 [Keystone Identity Service (public endpoint)]
      community.general.ufw:
        rule: allow
        port: "5000"
        proto: tcp

    - name: Allow port 873 [Rsync Endpoint]
      community.general.ufw:
        rule: allow
        port: "873"
        proto: tcp

    - name: Allow port 873 [Rsync Endpoint]
      community.general.ufw:
        rule: allow
        port: "873"
        proto: tcp
    # sudo ufw allow 8776/tcp   #
    # sudo ufw allow 8774/tcp   #
    # sudo ufw allow 8386/tcp   #
    # sudo ufw allow 35357/tcp  #
    # sudo ufw allow 9292/tcp   #
    # sudo ufw allow 9696/tcp   #
    # sudo ufw allow 8004/tcp   #
    # sudo ufw allow 8777/tcp   #
