---
- name: Install and configure NGINX
  hosts: machine

  vars:
    openstack_ingress_ip: "10.147.19.197"
    openstack_ingress_adress: openstack.dev.jakoberpf.de

  tasks:
    - name: Install nginx reverse proxy
      become: yes
      apt:
        pkg:
          - nginx
        state: present
      register: apt_action
      retries: 100
      until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

    - name: Create the nginx config for {{ openstack_ingress_adress }}
      become: yes
      ansible.builtin.template:
        src: ../templates/nginx.openstack.j2
        dest: "/etc/nginx/sites-available/{{ openstack_ingress_adress }}"
      register: config

    - name: Create a symbolic link for {{ openstack_ingress_adress }}
      become: yes
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/{{ openstack_ingress_adress }}"
        dest: "/etc/nginx/sites-enabled/{{ openstack_ingress_adress }}"
        state: link

    - name: Remove system link of default config
      become: yes
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart nginx, in all cases
      ansible.builtin.service:
        name: nginx
        state: restarted
      when: config.changed
